main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('players/', views.players_index, name='index'),
    path('players/<int:player_id>/', views.players_detail, name='detail'),
    path('players/create/', views.PlayerCreate.as_view(), name='players_create'),
    path('players/<int:pk>/update/', views.PlayerUpdate.as_view(), name='players_update'),
    path('players/<int:pk>/delete/', views.PlayerDelete.as_view(), name='players_delete'),
    path('players/<int:player_id>/add_schedule/', views.add_schedule, name='add_schedule'),
    path('accounts/signup/', views.signup, name='signup'),
   
]

varsity/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
     path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse

from django.contrib.auth.models import User

# tuples
EVENTS = (
    ('A', 'Practice'),
    ('B', 'Game'),
)


# Create your models here.
class Player(models.Model):
    name = models.CharField(max_length=75)
    age = models.IntegerField()
    lifetime_ba = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
   

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'player_id': self.id})
    
class Schedule(models.Model):
    date = models.DateField('Game or Practice date')
    event = models.CharField(max_length=1, choices=EVENTS, default=EVENTS[0][0])
    
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.get_event_display()} on {self.date}"

main_app/forms.py
# forms.py

from django.forms import ModelForm
from .models import Schedule

class ScheduleForm(ModelForm):
  class Meta:
    model = Schedule
    fields = ['date', 'event']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from.models import Player
from .forms import ScheduleForm


# Create your views here.
def home(request):
    return render(request, 'home.html')
def about(request):
    return render(request, 'about.html')


@login_required
def players_index(request):
    players = Player.objects.filter(user=request.user)
    return render(request, 'players/index.html', { 'players' : players})


@login_required
def players_detail(request, player_id):
  player = Player.objects.get(id=player_id)
  schedule_form = ScheduleForm()
  print (player)
  return render(request, 'players/detail.html', { 'player': player, 'schedule_form' : schedule_form})

@login_required
def add_schedule(request, player_id):
  # create a ModelForm instance using the data in request.POST
  form = ScheduleForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it
    # has the cat_id assigned
    new_schedule = form.save(commit=False)
    new_schedule.player_id = player_id
    new_schedule.save()
    return redirect('detail', player_id=player_id)

def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in via code
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)


class PlayerCreate(LoginRequiredMixin, CreateView):
    model = Player
    fields = ['name', 'age', 'lifetime_ba',]
    
    def form_valid(self, form):
       form.instance.user = self.request.user
       return super().form_valid(form)

class PlayerUpdate(LoginRequiredMixin, UpdateView):
    model = Player
    fields = ['name', 'age', 'lifetime_ba',]

class PlayerDelete(LoginRequiredMixin, DeleteView):
    model = Player
    success_url = '/players'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}


    <h1>League Finder </h1>
<hr>
<p>Find a league near you </p>
<!-- <footer>All Rights Reserved, &copy; 2022 Cat Collector</footer> -->
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>


</head>



    <nav>
        <div class="nav-wrapper  green accent-3">
            
        </div>
    </nav>
    <header class="navbar-fixed green accent-2">
        <nav>
            <div class="nav-wrapper  green accent-3">
                <ul>
                    <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;Varsity</a></li>

                </ul>
                <ul class="right">
                    <!-- changes below -->
                    <li><a href="{% url 'about' %}">About</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'players_create' %}">Add a Player</a></li>

                    <li><a href="{% url 'index' %}">View All Players</a></li>
                    <li><a href="{% url 'logout' %}">Log Out</a></li>
                    {% else %}
                 
                    <!-- New Sign Up link -->
                    <li><a href="{% url 'signup' %}">Sign Up</a></li>
                    <li><a href="{% url 'login' %}">Log In</a></li>
                    {% endif %}
                </ul>

            </div>
        </nav>
    </header>
    <main class="container">
        {% block content %}

        {% endblock %}
    </main>
    <footer class="page-footer green accent-2">
        <div>All Rights Reserved, &copy; 2023 Varsity &nbsp;</div>
    </footer>


</body>

</html>

main_app/templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Document</title>
</head>

<body class="bg">
    {% extends 'base.html' %}
    {% load static %}
    {% block content %}
    <h1>Every Game Matters</h1>

 
    {% endblock %}
</body>

</html>

main_app/templates/main_app/player_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Player</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' player.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/player_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add player</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
        <!-- Render the inputs inside of <tr>s & <td>s -->
        {{ form.as_table }}
    </table>
    <input type="submit" value="Add!" class="btn">
</form>
{% endblock %}

main_app/templates/players/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Player Details</h1>

<div class="row">
  <div class="col s6">

 


    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ player.name }}</span>
        <p>Age: {{ player.age }}</p>
        <p>LifeTime Ba: {{ player.lifetime_ba|linebreaks }}</p>
        {% if player.age > 0 %}
       
        {% else %}
        <p>Age: Rookie1</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'players_update' player.id %}">Update</a>
        <a href="{% url 'players_delete' player.id %}">Delete</a>
      </div>
    </div>
  </div>
  <!-- New Markup Below -->
  <div class="col s6">
    <form action="{% url 'add_schedule' player.id %}" method="POST">
      {% csrf_token %}
      <!-- Render the inputs -->
      {{ schedule_form.as_p }}
      <input type="submit" class="btn" value="Add Game or Practice">
    </form>


    <table class="striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Schedule</th>
        </tr>
      </thead>
      <tbody>
        {% for schedule in player.schedule_set.all %}
        <tr>
          <td>{{schedule.date}}</td>
          <td>{{schedule.get_event_display}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <!-- New Markup Above -->
</div>
<script>
  
  const dateEl = document.getElementById('id_date');
  console.log(dateEl)
  // M is Materialize's global variable
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
  const selectEl = document.getElementById('id_event');
  M.FormSelect.init(selectEl);
// </script>

{% endblock %}

main_app/templates/players/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Player List</h1>


{% for player in players %}
<!-- old one below  -->
  <div class="card">
    <a href="{% url 'detail' player.id %}">
    <div class="card-content">
      <span class="card-title">{{ player.name }}</span> </a>
      <p>Age: {{ player.age }}</p>
      <p>LifeTimeBA: {{ player.lifetime_ba }}</p>
   
      
    </div>
    </a>
    <div class="card-action">
        <a href="{% url 'players_update' player.id %}">Edit</a>
        <a href="{% url 'players_delete' player.id %}">Delete</a>
      </div>
      
  </div>
{% endfor %}

{% endblock %}